apiVersion: v1
kind: Secret
metadata:
  name: {{ include "upload-api.fullname" . }}-secrets
  labels:
    {{- include "upload-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3_ACCESS_KEY: "CHANGE_ME"
  S3_SECRET_KEY: "CHANGE_ME"

